# Generated by Django 3.2.3 on 2021-05-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albamon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=500)),
                ('detail_info', models.TextField()),
                ('pay', models.FloatField()),
                ('work', models.TextField()),
                ('applicant', models.IntegerField()),
            ],
        ),
    ]
