# Generated by Django 3.2.3 on 2021-05-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albaapp', '0002_auto_20210522_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albamon',
            name='pay',
            field=models.PositiveIntegerField(default=8720),
        ),
    ]
